//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAP_Seguros.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaCubrimiento
    {
        public int IdPoliza { get; set; }
        public int IdCubrimiento { get; set; }
        public byte Porcentaje { get; set; }
    }
}
